#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config normal_border_color "#191a22"
bspc config focused_border_color "#d9dbe3"

bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.5

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config honor_size_hints true

bspc rule -a Pcmanfm state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nitrogen state=floating

bspc rule -a "pixel engine" state=floating

bspc config top_padding 20
